"""
Reference implementations, written the way a C/C++/Java brain writes them:
explicit indices, explicit accumulation, one element at a time.

Every one of these is *correct*. That's the point — correctness was never
the problem. Your job in vectorized.py is to produce the same numbers
without a single Python-level loop over the data.

Do not edit this file. It's the ground truth your vectorized versions get
checked against.
"""

import numpy as np


def vector_add(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    n = a.shape[0]
    out = np.zeros(n)
    for i in range(n):
        out[i] = a[i] + b[i]
    return out


def dot(a: np.ndarray, b: np.ndarray) -> float:
    n = a.shape[0]
    total = 0.0
    for i in range(n):
        total += a[i] * b[i]
    return total


def matvec(A: np.ndarray, x: np.ndarray) -> np.ndarray:
    n, m = A.shape
    out = np.zeros(n)
    for i in range(n):
        total = 0.0
        for j in range(m):
            total += A[i, j] * x[j]
        out[i] = total
    return out


def matmul(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    n, k = A.shape
    k2, m = B.shape
    assert k == k2
    out = np.zeros((n, m))
    for i in range(n):
        for j in range(m):
            total = 0.0
            for p in range(k):
                total += A[i, p] * B[p, j]
            out[i, j] = total
    return out


def outer(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    n, m = a.shape[0], b.shape[0]
    out = np.zeros((n, m))
    for i in range(n):
        for j in range(m):
            out[i, j] = a[i] * b[j]
    return out


def pairwise_sq_dists(X: np.ndarray, Y: np.ndarray) -> np.ndarray:
    """Squared Euclidean distance between every row of X (n,d) and every row of Y (m,d) -> (n,m)."""
    n, d = X.shape
    m, d2 = Y.shape
    assert d == d2
    out = np.zeros((n, m))
    for i in range(n):
        for j in range(m):
            total = 0.0
            for p in range(d):
                diff = X[i, p] - Y[j, p]
                total += diff * diff
            out[i, j] = total
    return out


def row_l2_normalize(X: np.ndarray) -> np.ndarray:
    """Scale each row of X (n,d) to unit L2 norm."""
    n, d = X.shape
    out = np.zeros((n, d))
    for i in range(n):
        total = 0.0
        for j in range(d):
            total += X[i, j] * X[i, j]
        norm = total ** 0.5
        for j in range(d):
            out[i, j] = X[i, j] / norm
    return out


def softmax(X: np.ndarray) -> np.ndarray:
    """Row-wise softmax of X (n,d), numerically stable."""
    n, d = X.shape
    out = np.zeros((n, d))
    for i in range(n):
        row_max = X[i, 0]
        for j in range(1, d):
            if X[i, j] > row_max:
                row_max = X[i, j]
        total = 0.0
        for j in range(d):
            out[i, j] = np.exp(X[i, j] - row_max)
            total += out[i, j]
        for j in range(d):
            out[i, j] /= total
    return out


def weighted_row_average(X: np.ndarray, w: np.ndarray) -> np.ndarray:
    """Weighted average of the rows of X (n,d) with weights w (n,) -> (d,)."""
    n, d = X.shape
    out = np.zeros(d)
    weight_total = 0.0
    for i in range(n):
        weight_total += w[i]
    for j in range(d):
        total = 0.0
        for i in range(n):
            total += w[i] * X[i, j]
        out[j] = total / weight_total
    return out


def batch_matmul(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    """Batched matmul: A (batch,n,k), B (batch,k,m) -> (batch,n,m)."""
    batch, n, k = A.shape
    batch2, k2, m = B.shape
    assert batch == batch2 and k == k2
    out = np.zeros((batch, n, m))
    for b in range(batch):
        for i in range(n):
            for j in range(m):
                total = 0.0
                for p in range(k):
                    total += A[b, i, p] * B[b, p, j]
                out[b, i, j] = total
    return out
